[package]
name = "rust_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.9.0"
async-trait = "0.1.83"
json = "0.12.4"
rand = "0.8.5"
serde = "1.0.210"
tokio = { version = "1.40.0", features = ["full"] }
